Revert to globalize 5.0.1
globalize 5.1.0 causes tests to fail, not sure why...

```
API::V1::CategoriesTest#test_an_API_user_should_be_able_to_create_a_category:
NoMethodError: Entity::Category missing attribute `name' on #<Category:0x007f88cbc18378>
test/controllers/api/v1/categories_test.rb:95:in `block in <class:CategoriesTest>'
```